#!/usr/bin/env bash
#
# Amina Travel — one-shot provisioning for a FRESH Ubuntu VPS.
#
#   curl -fsSL https://raw.githubusercontent.com/ghassen-git/amina-travel/main/deploy/provision.sh | bash
#
# Brings a bare box all the way to a running stack: hardening, swap, Docker, the repo,
# a generated deploy/.env, a self-signed origin cert for Cloudflare "Full", and the
# compose stack itself. Safe to re-run — every step checks before acting, and an
# existing deploy/.env is never overwritten.
#
# Integration secrets (Cloudinary, TunisiaBeds, SMTP) are deliberately left blank: they
# don't belong in a public repo. The services degrade gracefully without them and they
# get filled in afterwards over SSH.
set -euo pipefail

REPO_URL="https://github.com/ghassen-git/amina-travel.git"
APP_DIR="/opt/amina-travel"
DOMAIN="${DOMAIN:-aminatravel.org}"
COMPOSE="docker compose -f docker-compose.prod.yml"

# Deploy key so the stack can be managed over SSH afterwards. Public half only — harmless
# on its own. Revoke any time by deleting this line from /root/.ssh/authorized_keys.
DEPLOY_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIERwyewdnZoXYwjAoN8x1GpHWQYWWiYpsL6y7FeI4vXx claude-code-deploy@amina"

step() { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }

[ "$(id -u)" -eq 0 ] || { echo "Run as root."; exit 1; }

step "1/8  Deploy key"
mkdir -p /root/.ssh && chmod 700 /root/.ssh
touch /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys
grep -qF "${DEPLOY_KEY%% *} ${DEPLOY_KEY#* }" /root/.ssh/authorized_keys 2>/dev/null \
  || grep -qF "claude-code-deploy@amina" /root/.ssh/authorized_keys \
  || echo "$DEPLOY_KEY" >> /root/.ssh/authorized_keys
echo "installed"

step "2/8  Base packages + firewall + fail2ban"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git openssl ufw fail2ban unattended-upgrades >/dev/null
ufw allow 22/tcp >/dev/null; ufw allow 80/tcp >/dev/null; ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
systemctl enable --now fail2ban >/dev/null 2>&1 || true
echo "ufw active, fail2ban running"

step "3/8  Swap (4 GB — 4 GB RAM alone OOMs the Next/.NET builds)"
if ! swapon --show | grep -q .; then
  fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  echo "4G swap added"
else
  echo "swap already present — skipped"
fi

step "4/8  Docker Engine + Compose plugin"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh >/dev/null
fi
docker --version && docker compose version

step "5/8  Source at $APP_DIR"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --all --quiet
  git -C "$APP_DIR" checkout main --quiet
  git -C "$APP_DIR" pull --quiet
  git -C "$APP_DIR" submodule update --init --recursive --quiet
else
  git clone --recurse-submodules --quiet "$REPO_URL" "$APP_DIR"
fi
echo "at $(git -C "$APP_DIR" rev-parse --short HEAD)"

step "6/8  deploy/.env"
ENV_FILE="$APP_DIR/deploy/.env"
if [ -f "$ENV_FILE" ]; then
  echo "already exists — left untouched"
else
  cat > "$ENV_FILE" <<EOF
# Generated by provision.sh. Secrets below are unique to this machine.
DOMAIN=$DOMAIN

POSTGRES_USER=amina
POSTGRES_PASSWORD=$(openssl rand -hex 24)
POSTGRES_DB=amina_travel

# JWT signing secret — no default in the app; empty 500s every request (IDX10703).
JWT_SIGNING_KEY=$(openssl rand -hex 32)

# Integrations — filled in over SSH after provisioning. Empty degrades gracefully:
# uploads 503, contact form 503, no supplier hotels, mock bank instead of Clictopay.
CLOUDINARY_URL=
TUNISIABEDS_LOGIN=
TUNISIABEDS_PASSWORD=
SMTP_USER=
SMTP_PASSWORD=
SMTP_TO=direction.aminatravel@gmail.com
CLICTOPAY_USERNAME=
CLICTOPAY_PASSWORD=
CLICTOPAY_BASE_URL=https://test.clictopay.com
EOF
  chmod 600 "$ENV_FILE"
  echo "written (generated POSTGRES_PASSWORD + JWT_SIGNING_KEY)"
fi

step "7/8  Self-signed origin cert (Cloudflare SSL mode \"Full\")"
CERT_DIR="$APP_DIR/deploy/nginx/certs"
mkdir -p "$CERT_DIR"
if [ ! -f "$CERT_DIR/origin.pem" ]; then
  openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
    -keyout "$CERT_DIR/origin.key" -out "$CERT_DIR/origin.pem" \
    -subj "/CN=$DOMAIN" \
    -addext "subjectAltName=DNS:$DOMAIN,DNS:*.$DOMAIN" 2>/dev/null
  chmod 600 "$CERT_DIR/origin.key"
  echo "generated"
else
  echo "already present — skipped"
fi

step "8/8  Build & start the stack (several minutes on 1 core)"
cd "$APP_DIR/deploy"
$COMPOSE --env-file .env up -d --build
# Rebuilt web/admin get new container IPs and nginx caches the old ones (→ 502).
$COMPOSE restart nginx
$COMPOSE ps

step "Verify (from the box, bypassing Cloudflare)"
sleep 5
printf 'health : '; curl -s -m 10 -H "Host: api.$DOMAIN"   http://localhost/health || echo FAILED
printf '\nsite   : '; curl -s -m 10 -o /dev/null -w '%{http_code}' -H "Host: $DOMAIN"       http://localhost/
printf '\nadmin  : '; curl -s -m 10 -o /dev/null -w '%{http_code}' -H "Host: admin.$DOMAIN" http://localhost/
printf '\nreels  : '; curl -s -m 10 -o /dev/null -w '%{http_code}' -H "Host: api.$DOMAIN"   http://localhost/api/reels
printf '\n\nDone. 200s above mean the stack is healthy.\n'
printf 'Remaining: integration secrets, admin user, hotel sync — all doable over SSH.\n'
